// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/objectbox/objectbox_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 600744434621095931),
    name: 'ScreenshotEntity',
    lastPropertyId: const obx_int.IdUid(14, 7739490019654648834),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3706152324678215829),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7023793627489041659),
        name: 'appId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 755288377846488545),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3679762910709058957),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4579994230589263606),
        name: 'capturedAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 360277996769823230),
        name: 'indexedAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6782086456134829284),
        name: 'width',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 839746291008913966),
        name: 'height',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8372239392088160834),
        name: 'fileSizeBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1431467765007224391),
        name: 'extractedText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5189184286676698744),
        name: 'tagsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4486885043942402449),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2005059483032248073),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5265260427299486085),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7739490019654648834),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 2257159740347098099),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 1853320434411549886),
        name: 'textBlocks',
        targetId: const obx_int.IdUid(2, 6917378817221049129),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6917378817221049129),
    name: 'TextBlockEntity',
    lastPropertyId: const obx_int.IdUid(8, 6673802799610011179),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 799922033694723571),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4667820326858414165),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1823238620560094752),
        name: 'confidence',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8270546729022063796),
        name: 'boxLeft',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4000006501516465960),
        name: 'boxTop',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4737089169307684592),
        name: 'boxWidth',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6943942621993781023),
        name: 'boxHeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6673802799610011179),
        name: 'screenshotId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 6534838029152096322),
        relationField: 'screenshot',
        relationTarget: 'ScreenshotEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6917378817221049129),
    lastIndexId: const obx_int.IdUid(3, 6534838029152096322),
    lastRelationId: const obx_int.IdUid(1, 1853320434411549886),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ScreenshotEntity: obx_int.EntityDefinition<ScreenshotEntity>(
      model: _entities[0],
      toOneRelations: (ScreenshotEntity object) => [],
      toManyRelations: (ScreenshotEntity object) => {
        obx_int.RelInfo<ScreenshotEntity>.toMany(1, object.obId):
            object.textBlocks,
      },
      getId: (ScreenshotEntity object) => object.obId,
      setId: (ScreenshotEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (ScreenshotEntity object, fb.Builder fbb) {
        final appIdOffset = fbb.writeString(object.appId);
        final filePathOffset = fbb.writeString(object.filePath);
        final capturedAtOffset = fbb.writeString(object.capturedAt);
        final indexedAtOffset = fbb.writeString(object.indexedAt);
        final extractedTextOffset = fbb.writeString(object.extractedText);
        final tagsJsonOffset = fbb.writeString(object.tagsJson);
        final categoryOffset = fbb.writeString(object.category);
        final summaryOffset = object.summary == null
            ? null
            : fbb.writeString(object.summary!);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(15);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, appIdOffset);
        fbb.addOffset(2, filePathOffset);
        fbb.addOffset(3, capturedAtOffset);
        fbb.addOffset(4, indexedAtOffset);
        fbb.addInt64(5, object.width);
        fbb.addInt64(6, object.height);
        fbb.addInt64(7, object.fileSizeBytes);
        fbb.addOffset(8, extractedTextOffset);
        fbb.addOffset(9, tagsJsonOffset);
        fbb.addOffset(10, categoryOffset);
        fbb.addOffset(11, summaryOffset);
        fbb.addBool(12, object.isFavorite);
        fbb.addOffset(13, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ScreenshotEntity()
          ..obId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..appId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..filePath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..capturedAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..indexedAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..width = const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
          ..height = const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
          ..fileSizeBytes = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..extractedText = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..tagsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..category = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 24, '')
          ..summary = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 26)
          ..isFavorite = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            28,
            false,
          )
          ..embedding = const obx_int.Float32ListReader().vTableGet(
            buffer,
            rootOffset,
            30,
            Float32List(0),
          );
        obx_int.InternalToManyAccess.setRelInfo<ScreenshotEntity>(
          object.textBlocks,
          store,
          obx_int.RelInfo<ScreenshotEntity>.toMany(1, object.obId),
        );
        return object;
      },
    ),
    TextBlockEntity: obx_int.EntityDefinition<TextBlockEntity>(
      model: _entities[1],
      toOneRelations: (TextBlockEntity object) => [object.screenshot],
      toManyRelations: (TextBlockEntity object) => {},
      getId: (TextBlockEntity object) => object.obId,
      setId: (TextBlockEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (TextBlockEntity object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(9);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, textOffset);
        fbb.addFloat64(2, object.confidence);
        fbb.addFloat64(3, object.boxLeft);
        fbb.addFloat64(4, object.boxTop);
        fbb.addFloat64(5, object.boxWidth);
        fbb.addFloat64(6, object.boxHeight);
        fbb.addInt64(7, object.screenshot.targetId);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = TextBlockEntity()
          ..obId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..text = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..confidence = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..boxLeft = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..boxTop = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..boxWidth = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..boxHeight = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          );
        object.screenshot.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.screenshot.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ScreenshotEntity] entity fields to define ObjectBox queries.
class ScreenshotEntity_ {
  /// See [ScreenshotEntity.obId].
  static final obId = obx.QueryIntegerProperty<ScreenshotEntity>(
    _entities[0].properties[0],
  );

  /// See [ScreenshotEntity.appId].
  static final appId = obx.QueryStringProperty<ScreenshotEntity>(
    _entities[0].properties[1],
  );

  /// See [ScreenshotEntity.filePath].
  static final filePath = obx.QueryStringProperty<ScreenshotEntity>(
    _entities[0].properties[2],
  );

  /// See [ScreenshotEntity.capturedAt].
  static final capturedAt = obx.QueryStringProperty<ScreenshotEntity>(
    _entities[0].properties[3],
  );

  /// See [ScreenshotEntity.indexedAt].
  static final indexedAt = obx.QueryStringProperty<ScreenshotEntity>(
    _entities[0].properties[4],
  );

  /// See [ScreenshotEntity.width].
  static final width = obx.QueryIntegerProperty<ScreenshotEntity>(
    _entities[0].properties[5],
  );

  /// See [ScreenshotEntity.height].
  static final height = obx.QueryIntegerProperty<ScreenshotEntity>(
    _entities[0].properties[6],
  );

  /// See [ScreenshotEntity.fileSizeBytes].
  static final fileSizeBytes = obx.QueryIntegerProperty<ScreenshotEntity>(
    _entities[0].properties[7],
  );

  /// See [ScreenshotEntity.extractedText].
  static final extractedText = obx.QueryStringProperty<ScreenshotEntity>(
    _entities[0].properties[8],
  );

  /// See [ScreenshotEntity.tagsJson].
  static final tagsJson = obx.QueryStringProperty<ScreenshotEntity>(
    _entities[0].properties[9],
  );

  /// See [ScreenshotEntity.category].
  static final category = obx.QueryStringProperty<ScreenshotEntity>(
    _entities[0].properties[10],
  );

  /// See [ScreenshotEntity.summary].
  static final summary = obx.QueryStringProperty<ScreenshotEntity>(
    _entities[0].properties[11],
  );

  /// See [ScreenshotEntity.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<ScreenshotEntity>(
    _entities[0].properties[12],
  );

  /// See [ScreenshotEntity.embedding].
  static final embedding = obx.QueryHnswProperty<ScreenshotEntity>(
    _entities[0].properties[13],
  );

  /// see [ScreenshotEntity.textBlocks]
  static final textBlocks =
      obx.QueryRelationToMany<ScreenshotEntity, TextBlockEntity>(
        _entities[0].relations[0],
      );
}

/// [TextBlockEntity] entity fields to define ObjectBox queries.
class TextBlockEntity_ {
  /// See [TextBlockEntity.obId].
  static final obId = obx.QueryIntegerProperty<TextBlockEntity>(
    _entities[1].properties[0],
  );

  /// See [TextBlockEntity.text].
  static final text = obx.QueryStringProperty<TextBlockEntity>(
    _entities[1].properties[1],
  );

  /// See [TextBlockEntity.confidence].
  static final confidence = obx.QueryDoubleProperty<TextBlockEntity>(
    _entities[1].properties[2],
  );

  /// See [TextBlockEntity.boxLeft].
  static final boxLeft = obx.QueryDoubleProperty<TextBlockEntity>(
    _entities[1].properties[3],
  );

  /// See [TextBlockEntity.boxTop].
  static final boxTop = obx.QueryDoubleProperty<TextBlockEntity>(
    _entities[1].properties[4],
  );

  /// See [TextBlockEntity.boxWidth].
  static final boxWidth = obx.QueryDoubleProperty<TextBlockEntity>(
    _entities[1].properties[5],
  );

  /// See [TextBlockEntity.boxHeight].
  static final boxHeight = obx.QueryDoubleProperty<TextBlockEntity>(
    _entities[1].properties[6],
  );

  /// See [TextBlockEntity.screenshot].
  static final screenshot =
      obx.QueryRelationToOne<TextBlockEntity, ScreenshotEntity>(
        _entities[1].properties[7],
      );
}
